spring.application.name=swift-message-relay-service

relay.polling.interval=5000

server.port=8873

spring.datasource.url=jdbc:postgresql://localhost:5433/SWIFTAPI
spring.datasource.username=postgres
spring.datasource.password=akshay@its

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

saa.payment.mq=PAYMENT.OUT.QUEUE

# The default port for ActiveMQ is 61616
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
