spring.application.name=ISOBridge

spring.profiles.active=dev
server.servlet.context-path=/iso-bridge-service

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

base.bank.bic=DBAKSARIXXX

# The default port for ActiveMQ is 61616
spring.activemq.broker-url=tcp://host.docker.internal:61616
spring.activemq.user=admin
spring.activemq.password=admin


