spring.application.name=swift-saa-simulator-service

saa.response.mq=SAA.RESPONSE.MQ
payment.out.queue=PAYMENT.OUT.MQ

# The default port for ActiveMQ is 61616
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

app.security.encryption-key=iC7@Rq0XhE!U3nL#

spring.datasource.url=jdbc:postgresql://localhost:5433/SWIFTAPI
spring.datasource.username=postgres
spring.datasource.password=akshay@its

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect